<?php
// Assuming session_start() has already been called
// Assuming base_url() function is defined elsewhere
// Assuming $connection is your database connection object
?>

<div class="sidebar" id="sidebar">
   <div class="sidebar-inner slimscroll">
      <div id="sidebar-menu" class="sidebar-menu">
         <nav class="greedys sidebar-horizantal">
            <ul class="list-inline-item list-unstyled links">
               <li class="menu-title">
                  <span>Main</span>
               </li>
               <li class="submenu">
                  <a href="#"><i class="la la-dashboard"></i> <span> Dashboard</span> <span class="menu-arrow"></span></a>
                  <ul>
                     <li><a href="admin-dashboard.html">Admin Dashboard</a></li>
                     <li><a href="employee-dashboard.html">Employee Dashboard</a></li>
                  </ul>
               </li>
               <!-- Other menu items... -->
            </ul>
            <button class="viewmoremenu">More Menu</button>
            <ul class="hidden-links hidden">
               <!-- Additional menu items will be generated by PHP based on session department -->
               <?php
               if (strtolower($_SESSION['department']) == 'hr') {
                  // HR Department menu items
                  echo "
                  <li class='menu-title'>
                     <span>HR</span>
                  </li>
                  <li><a href='" . base_url('hr/dashboard') . "'><i class='la la-dashboard'></i><span>Dashboard</span></a></li>
                  <li><a href='" . base_url('hr/calendar') . "'><i class='fa-regular fa-calendar'></i><span>Calendar</span></a></li>
                  <li><a href='" . base_url('hr/announcement') . "'><i class='la la-bullhorn'></i><span>Announcements</span></a></li>
    <li class='submenu reports'>
        <a href='#' class=''><i class='la la-file-text'></i><span>Reports</span><span class='menu-arrow'></span></a>
        <ul>
        <li><a href='hr_emp_performance.html'>Employee Performance |</a></li>

        <li><a href='" . base_url('hr/reports/salary') . "'>Salary Report |</a></li>
        <li><a href='" . base_url('hr/reports/timesheet') . "'>Timesheet</a></li>

            <li><a href='" . base_url('hr/employees/attendance') . "'>Attendance</a></li>
            <li><a href='" . base_url('hr/employees/leaves') . "'>Leaves</a></li>
        </ul>
    </li>
    <li class='submenu employees'>
        <a href='#'><i class='la la-user'></i><span>Employees</span><span class='menu-arrow'></span></a>
        <ul>
            <li><a href='" . base_url('hr/employees') . "'>Manage</a></li>
            <li><a href='" . base_url('hr/departments') . "'>Designations</a></li>
            <li><a href='" . base_url('hr/employees/shifts') . "'>Shifts & Schedules</a></li>
        </ul>
    </li>
    <li class='submenu payroll'>
        <a href='#' class=''><i class='la la-money'></i><span>Payroll</span><span class='menu-arrow'></span></a>
        <ul>
            <li><a href='hr_emp_overview.html'>Salary Rate |</a></li>
            <li><a href='hr_emp_manage.html'>Bonuses & Commissions |</a></li>
            <li><a href='hr_emp_designations.html'>Deductions |</a></li>
        </ul>
    </li>
    <li class='submenu forms'>
        <a href='#' class=''><i class='la la-object-group'></i><span>Forms</span><span class='menu-arrow'></span></a>
        <ul>
            <li><a href='" . base_url('forms') . "'>Apply</a></li>
            <li><a href='" . base_url('hr/pendingrequests') . "'>Pending</a></li>
            <li><a href='" . base_url('hr/historyrequests') . "'>History</a></li>
        </ul>
    </li>
"
                  
                  ;
               } else {
                  // For other departments
                  $employee_id = $_SESSION['emp_id'];
                  // Perform the query to get employee details
                  // Assuming you're using a MySQL database
                  $query = "SELECT roles FROM department_roles WHERE assigned_emp = $employee_id";
                  // Assuming $connection is your database connection object
                  $result = mysqli_query($connection, $query);
                  if ($result) {
                     $row = mysqli_fetch_assoc($result);
                     $position = $row['roles'];
                     // Check if the position is 'head'
                     if ($position == 'head') {
                        echo "
                        <li class='menu-title'>
                           <span>Head</span>
                        </li>
                        
                        <li><a href='" . base_url('employee/dashboard') . "'><i class='la la-dashboard'></i><span>Dashboard (Employee)</span></a></li>
                        <li class='submenu forms'>
                           <a href='#'><i class='la la-object-group'></i><span>Forms</span><span class='menu-arrow'></span></a>
                           <ul>
                              <li><a href='" . base_url('forms') . "'>Apply</a></li>
                              <li><a href='" . base_url('employee/pendingrequests') . "'>Pending</a></li>
                              <li><a href='" . base_url('forms/history') . "'>History</a></li>
                                  <li><a href='" . base_url('forms/history') . "'>History</a></li>
                           </ul>
                        </li>";
                     } else {
                        echo "
                        <li class='menu-title'>
                           <span>Employee</span>
                        </li>
                        <li><a href='" . base_url('employee/dashboard') . "'><i class='la la-dashboard'></i><span>Dashboard (Employee)</span></a></li>
                        <!-- Add other menu items for non-head position here -->";
                     }
                  } else {
                     // Handle query error
                     echo "Error: " . mysqli_error($connection);
                  }
               }
               ?>
            </ul>
         </nav>
      </div>
   </div>
</div>
